name: Security CI

on: [push, pull_request]

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit safety

    - name: Run Bandit (SAST)
      run: |
        bandit -r app/ -f html -o bandit_report.html || true

    - name: Run Safety (SCA)
      run: |
        safety check -r requirements.txt --full-report --output safety_report.txt || true

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit_report.html
          safety_report.txt