name: Security and Quality CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit safety flake8 black

    - name: Run Bandit (SAST)
      run: |
        bandit -r  app/ config.py run.py -f html -o bandit_report.html || true

    - name: Run Safety check (используем старую работающую версию)
      run: |
        safety check -r requirements.txt --full-report > safety_report.txt || true
        echo "=== Safety Check Report ==="
        cat safety_report.txt || true

    - name: Format code with Black
      run: |
        black app/ config.py run.py
        echo "✅ Code formatted with Black"

    - name: Check code formatting with Black
      run: |
        black --check app/ config.py run.py || true

    - name: Lint with flake8
      run: |
        flake8 app/ config.py run.py --max-line-length=88 --ignore=E203,W503 --statistics || true

    - name: Upload Bandit report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: bandit_report.html

    - name: Upload Safety report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: safety-reports
        path: safety_report.txt